public with sharing class LudoConstants {
    public static final String PLAYERNAMETEXT = 'playerName';
    public static final String PLAYERTYPETEXT = 'playerType';
    public static final String PLAYERBOARDIDTEXT = 'playerBoardId';
    public static final String PLAYERJOINEDNOTEXT = 'playerJoinedNo';
    public static final String MAXPLAYERCOUNTTEXT = 'maxPlayerCount';
    public static final String ISLASTPLAYERTEXT = 'isLastPlayer';

}
